# Generated by Django 5.0.7 on 2024-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rue',
            name='h',
            field=models.CharField(default=13, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rue',
            name='x',
            field=models.CharField(default=5.36, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rue', 
            name='y',
            field=models.CharField(default=-4.0083, max_length=250),
            preserve_default=False,
        ),
    ]
