# Generated by Django 5.0.4 on 2024-08-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rue_h_rue_x_rue_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='rue',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rue',
            name='commune',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rue',
            name='h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rue',
            name='nom_rue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rue',
            name='quartier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rue',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rue',
            name='y',
            field=models.FloatField(),
        ),
    ]
