# Generated by Django 5.0.4 on 2024-08-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rue_url_alter_rue_commune_alter_rue_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rue',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
