# Generated by Django 5.0.4 on 2024-09-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_rue_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rue',
            name='url',
        ),
    ]
