# Generated by Django 5.0.4 on 2025-03-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_rue_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rue',
            name='h',
        ),
    ]
