# Generated by Django 5.0.4 on 2025-04-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_rue_h'),
    ]

    operations = [
    ]
