# Generated by Django 5.0.4 on 2025-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_voie_delete_rue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_voie', models.CharField(max_length=255)),
                ('qr_code_url', models.TextField()),
                ('suggestion', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suggestions',
                'managed': False,
            },
        ),
    ]
