# Generated by Django 5.2.7 on 2025-10-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_signalementprobleme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_voie', models.CharField(max_length=255)),
                ('qr_code_url', models.TextField()),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('probleme', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('voie', models.ForeignKey(db_column='voie_id', on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='myapp.voie')),
            ],
            options={
                'db_table': 'problemes',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='SignalementProbleme',
        ),
    ]
