# Generated by Django 5.2.7 on 2025-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_probleme_delete_signalementprobleme'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publicites/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='publicites/videos/')),
                ('type_media', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'publicites',
            },
        ),
    ]
