# Generated by Django 5.2.7 on 2025-11-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_publicites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voie',
            options={'managed': False, 'permissions': [('can_add_suggestion_voie', 'Peut ajouter une suggestion de voie')]},
        ),
    ]
