# Generated by Django 5.2.7 on 2025-11-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_voie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voie',
            options={'managed': False, 'permissions': [('view_dashboard_voies', 'Voir Dashboard Voies'), ('can_add_suggestion_voie', 'Peut ajouter une nouvelle description de voie')]},
        ),
    ]
