# Generated by Django 5.2.7 on 2025-11-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_voie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voie',
            options={'managed': False, 'permissions': [('view_dashboard_voies', 'Voir Dashboard Voies'), ('can_add_suggestion_voie', 'Peut ajouter une nouvelle description de voie'), ('valider_cca', 'Valider Par CCA'), ('rejeter_cca', 'Refuser par CCA'), ('ajouter_suggestion_cca', 'Ajouter suggestion Par CCA'), ('valider_mo', 'Valider Par MO'), ('rejeter_mo', 'Refuser Par MO'), ('ajouter_suggestion_mo', 'Ajouter suggestion Par MO'), ('voir_suggestion_voie', 'Voir suggestion voie')]},
        ),
    ]
