# Generated by Django 5.2.7 on 2025-11-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_voie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voie',
            options={'managed': False, 'permissions': [('view_dashboard_voies', 'Voir Dashboard Voies'), ('can_add_suggestion_voie', 'Peut ajouter une nouvelle description de voie'), ('valider_cca', 'Valider Par CCA'), ('rejeter_cca', 'Refuser par CCA'), ('ajouter_suggestion_cca', 'Ajouter suggestion Par CCA'), ('valider_mo', 'Valider Par MO'), ('rejeter_mo', 'Refuser Par MO'), ('ajouter_suggestion_mo', 'Ajouter suggestion Par MO'), ('voir_suggestion_voie', 'Voir suggestion voie'), ('voir_suggestion_voie_attent_mo', 'Voir suggestion voie attente MO'), ('voir_suggestion_voie_attente_cca', 'Voir suggestion voie en attente CCA')]},
        ),
    ]
