# Generated by Django 5.2.7 on 2025-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_voie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toponymie',
            fields=[
                ('id_toponymie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pada', models.TextField(blank=True, null=True)),
                ('type_voie', models.TextField(blank=True, null=True)),
                ('nouvelle_description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=30, null=True)),
                ('toponyme', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('typologie', models.TextField(blank=True, null=True)),
                ('quartier_origine', models.TextField(blank=True, null=True)),
                ('id_voies', models.IntegerField(blank=True, null=True)),
                ('gid_commune', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateField(blank=True, null=True)),
                ('date_modif_toponyme', models.DateField(blank=True, null=True)),
                ('date_modif_description', models.DateField(blank=True, null=True)),
                ('validation_cs', models.BooleanField(default=False)),
                ('validation_coord', models.BooleanField(default=False)),
                ('validation_mo', models.BooleanField(default=False)),
                ('categorie', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('autoris_modification', models.TextField(blank=True, null=True)),
                ('auteur_modif_toponyme', models.TextField(blank=True, null=True)),
                ('auteur_modif_desc', models.TextField(blank=True, null=True)),
                ('hist_desc', models.TextField(blank=True, null=True)),
                ('hist_toponyme', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"501_siga_toponymie"',
                'permissions': [('list_toponyme', 'Voir List Toponyme'), ('ajouter_description_toponyme', 'Ajouter une nouvelle description toponyme'), ('voir_dashboard_toponyme', 'Voir Dashboard Toponyme')],
                'managed': False,
            },
        ),
    ]
