# Generated by Django 5.2.7 on 2025-11-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_toponymie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toponymie',
            options={'managed': False, 'permissions': [('list_toponyme', 'Voir List Toponyme'), ('ajouter_description_toponyme', 'Ajouter une nouvelle description toponyme'), ('voir_dashboard_toponyme', 'Voir Dashboard Toponyme'), ('valider_cs_topo', 'Valider Par CS TOPO'), ('rejeter_cs_topo', 'Refuser par CS TOPO'), ('valider_coord_topo', 'Valider Par CCA TOPO'), ('rejeter_coord_topo', 'Refuser par CCA TOPO'), ('valider_mo_topo', 'Valider Par MO TOPO'), ('rejeter_mo_topo', 'Refuser par MO TOPO')]},
        ),
    ]
