# Generated by Django 5.2.7 on 2025-11-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_toponymie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toponymie',
            options={'managed': False, 'permissions': [('list_toponyme', 'Voir List Toponyme'), ('ajouter_description_toponyme', 'Ajouter une nouvelle description toponyme'), ('voir_dashboard_toponyme', 'Voir Dashboard Toponyme'), ('valider_cs_topo', 'Valider Par CS TOPO'), ('rejeter_cs_topo', 'Refuser par CS TOPO'), ('valider_coord_topo', 'Valider Par CCA TOPO'), ('rejeter_coord_topo', 'Refuser par CCA TOPO'), ('valider_mo_topo', 'Valider Par MO TOPO'), ('rejeter_mo_topo', 'Refuser par MO TOPO'), ('voir_topo_attente_toponymie', 'Voir Toponymie en attente de Tponymie'), ('voir_topo_attente_CS', 'Voir Toponymie en attente de cs'), ('voir_topo_attente_CCA', 'Voir Toponymie en attente de CCA'), ('voir_topo_attente_mo', 'Voir Toponymie en attente de MO'), ('suggestion_topo_CS', 'Ajouter Suggestion TOPO CS'), ('suggestion_topo_CCA', 'Ajouter Suggestion TOPO CCA'), ('suggestion_topo_MO', 'Ajouter Suggestion TOPO MO')]},
        ),
    ]
