# Generated by Django 5.2.7 on 2026-01-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_toponymie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='voirie_panneautage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('id_voie', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('nom_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('localisati', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.BigIntegerField(blank=True, null=True)),
                ('secteur', models.BigIntegerField(blank=True, null=True)),
                ('class_pada', models.CharField(blank=True, max_length=50, null=True)),
                ('type_voie', models.CharField(blank=True, max_length=254, null=True)),
                ('validé', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'voirie_panneautage',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='publicites',
            name='image_pub',
            field=models.ImageField(blank=True, null=True, upload_to='publicites/images/'),
        ),
        migrations.AlterField(
            model_name='publicites',
            name='type_media',
            field=models.CharField(blank=True, choices=[('image', 'Image Publicitaire'), ('video', 'Vidéo'), ('none', 'Aucun')], null=True),
        ),
    ]
